### ISSUE TITLE
geometry leaks in daemon

### ISSUE THREAD

**Issue by ghost** [DaemonEngine/Daemon#950] opened 2023-11-01 20:05 UTC
Usstremor and tremor-2016 both have a geometry leak.

Apparently, tremor-2016 does [not](https://github.com/Masmblr/map-Tremor_2016_src/issues/1) have this leak in unvanquished, and I believe that kind of problem can not be related to gamelogic.

**Comment by slipher** [comment] 2023-11-02 00:05
I thought a geometry leak means that the brushes in a BSP do not fully enclose the inside of the map - that there is a path from the playable area of the map to the void outside that avoids brushes. Is that what you're talking about here?

**Comment by bmorel** [comment] 2023-11-02 00:14
From a _player_ point of a view, a geometry leak is when you can go out of the geometry. A player, or a gamelogic developper, is not necessarily able to understand if the leak comes from the bsp or from how the collisions are managed.
I do not know enough about what the BSP is or how the math are done to be able to say if it comes from the data or the code interpreting it, but the fact a leak exists in unvanquished but not in tremulous, with the same data, to me, seems to indicate a collision bug.
I know a bit the code of some collision handling in unvanquished, and I would be quite curious to see someone able to say with certainty if that stuff is buggy or not, so I think the best to do is to check with tremulous.
Of course, it might be that the dretch size changed between the games: in unv, it have a width of 30, and I could not find this info easily in the trem's code I use for reference, perhaps it was larger, but that would mean larger than a human, as well, so it would surprise me.

**Comment by VReaperV** [comment] 2024-01-30 14:19
This is likely the same bug is in rotcannon-garbage where you can fall through the tubes at the sides of the main area (e. g. in front of viewpos -456 -1024 -1365 173).

**Comment by VReaperV** [comment] 2024-09-02 22:47
The bug on usstremor has been fixed apparently by updating the map itself, but it still remains on other maps.

**Comment by VReaperV** [comment] 2024-10-25 09:15
Duplicate of #1307.

**Closed by VReaperV** 2024-10-25 09:15 UTC
Labels: T-Bug
