### ISSUE TITLE
Broken lantern/candle in metro map, light emitting shader is displayed

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#322] opened 2020-04-21 18:47 UTC
I've noticed this issue a long time ago, but #301 seems to also trigger it in Terminus. It may be time to look at it…

Look at those candles and lanterns, how they look in Unvanquished:

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172144-766.unvanquished-metro.jpg)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172144-766.unvanquished-metro.jpg)

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172202-942.unvanquished-metro.jpg)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172202-942.unvanquished-metro.jpg)

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172213-958.unvanquished-metro.jpg)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172213-958.unvanquished-metro.jpg)

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172244-926.unvanquished-metro.jpg)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172244-926.unvanquished-metro.jpg)

And how they look in Tremulous:

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192524-525.tremulous-metro.jpg)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192524-525.tremulous-metro.jpg)

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192532-741.tremulous-metro.jpg)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192532-741.tremulous-metro.jpg)

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192538-625.tremulous-metro.jpg)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192538-625.tremulous-metro.jpg)

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192906-579.tremulous-metro.jpg)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-192906-579.tremulous-metro.jpg)

Along with the flame, you'll notice those square textures in NetRadiant (those things are `misc_model` entities so they are meant to be baked in BSP):

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-170352-447.netradiant-metro.png)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-170352-447.netradiant-metro.png)

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-170459-128.netradiant-metro.png)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-170459-128.netradiant-metro.png)

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-170549-380.netradiant-metro.png)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-170549-380.netradiant-metro.png)

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172345-143.netradiant-metro.png)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-172345-143.netradiant-metro.png)

Those squares textures are in fact… light emitting shaders, that's a clever hack to ship an md3 model with built-in lighting (with light orientation etc.). We see how those light emitting shaders are set:

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-194539-716.netradiant-metro.png)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-194539-716.netradiant-metro.png)

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-194543-140.netradiant-metro.png)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-194543-140.netradiant-metro.png)

[![metro lantern](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-200200-081.unvanquished-metro.jpg)](https://dl.illwieckz.net/b/daemon/bugs/metro-lantern/20200421-200200-081.unvanquished-metro.jpg)

The one floating above or in front of the lantern is meant to use the back splash feature of the light emitting shader to lit the ground or the wall.

This is the code for the square light emitting shader:

```c
//lanterne1.md3 self lightning
models/mapobjects/kosad/lanterne/lumieresoft
{
	qer_editorimage models/mapobjects/kosad/lanterne/lumieresoft
	qer_trans .2

	q3map_surfacelight 5000
	q3map_lightrgb 1 .8 .4
	q3map_backsplash 30 4

	{
		map $lightmap
		blendfunc filter
	}
}
```

What's weird is that this lightmap is not meant to be displayed at all so I don't know why there is a lightmap stage, maybe to be sure the compiler will not ignore the shader and the light will be emitted.

The `blendFunc filter` operation is the [default operation](https://github.com/DaemonEngine/Daemon/blob/0e001477c5c05249348efc8a612310c2bec63393/src/engine/renderer/tr_shader.cpp#L4697) to blend a lightmap over a diffuseMap. What's weird is that if we don't take in account this material is not meant to be rendered, this is a lightmap blended with nothing. This is like _undefined behaviour_.

Then, if we look at the code of the candle flame shader:

```c
textures/metro/kosad_flammebougie
{
	qer_editorimage textures/metro/kosad_flammebougie1

	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm trans

	cull disable
	deformvertexes autosprite2

	{
		animmap 50 textures/metro/kosad_flammebougie1 textures/metro/kosad_flammebougie2 textures/metro/kosad_flammebougie3 textures/metro/kosad_flammebougie4 textures/metro/kosad_flammebougie5 textures/metro/kosad_flammebougie6 textures/metro/kosad_flammebougie7 textures/metro/kosad_flammebougie8
		blendfunc add
	}
}
```

It's an animMap blended with `add` operation (like glow maps), added over… nothing.

Note that those pictures are jpeg with black bacground, the right operation may be `alphaFunc GT0` or `alphaFunc GE128`.

The blendFunc are usually used to blend multiple stage within shaders, that's not the same purpose.

This time, the material must be displayed, but not the way it is.

**Comment by bmorel** [comment] 2021-12-31 00:41
Is there is a way to get the map uploaded to the issue? I can't find any "metro" map.

**Comment by slipher** [comment] 2023-12-07 18:26
Related: https://github.com/DaemonEngine/Daemon/issues/730

**Comment by illwieckz** [comment] 2023-12-15 07:42
It looks like the “light emitting shader is displayed” issue is fixed:

![unvanquished_2023-12-15_024400_000](https://github.com/DaemonEngine/Daemon/assets/2311649/95549d13-9524-4239-987f-02dcda3b7c8a)

![unvanquished_2023-12-15_024822_000](https://github.com/DaemonEngine/Daemon/assets/2311649/b40c9969-4b9b-4510-b2ce-a6d2711c3181)

![unvanquished_2023-12-15_024852_000](https://github.com/DaemonEngine/Daemon/assets/2311649/1d1083cc-9e3c-43f7-bac4-5611f3ec9d6c)

![unvanquished_2023-12-15_024903_000](https://github.com/DaemonEngine/Daemon/assets/2311649/2c33268d-1ebf-4096-90b4-56c953866d33)

![unvanquished_2023-12-15_024947_000](https://github.com/DaemonEngine/Daemon/assets/2311649/d3434f56-aa3c-4b8c-9a6d-dfbd24b406a7)

So it remains the issue about the missing flame/fire sprite effect, let track this in a dedicated thread:

- https://github.com/DaemonEngine/Daemon/issues/997

**Comment by illwieckz** [comment] 2024-01-08 17:09
It's not fixed. I assume the above screenshots were mistakenly done with a branch I forgot about that would fix them in sources. Using the tremulous build it's still broken.

**Comment by VReaperV** [comment] 2024-10-23 15:40
This is fixed now by the autosprite stuff.

**Comment by slipher** [comment] 2024-10-31 04:44
Some of the unwanted surfaces are still there: https://github.com/DaemonEngine/Daemon/pull/1406#issuecomment-2448990540

Just the ones that were part of the flames were fixed.

**Comment by illwieckz** [comment] 2024-11-06 18:00
As a remind, I never seen those textures working on Unvanquished in the past (maybe with the legacy GL1 renderer, but never with the new one).

As said here in this comment: https://github.com/DaemonEngine/Daemon/pull/1406#issuecomment-2460415926

> The metro visible “visible light emitting shader” is a tricky one.
> 
> As a remind, the lantern, the candle, etc. come with some shaders having a single stage like this:
> 
> ```
> 	{
> 		map $lightmap
> 		blendfunc filter
> 	}
> ```
> 
> So we get floating lightmaps multiplied over whatever is behind.
> 
> I even don't know why it worked on Tremulous…
> 
> Maybe we can just strip them out…

It's probably better to just skip them. They could only work if the lightmap was exactly 1, as it would be like not applying any lightmap.

If Tremulous worked, it's either because of a bug, or because the engine skipped them in some ways…

**Comment by illwieckz** [comment] 2024-11-06 18:02
Actually, maybe overbright and clamping turned those lightmaps into `1`, so maybe it was just luck.

**Comment by VReaperV** [comment] 2024-11-06 19:24
I wonder why those were even there if they're invisible. Is it maybe some weird netradiant output or something?

**Comment by illwieckz** [comment] 2024-11-07 11:17
Nothing to do with NetRadiant, and NetRadiant doesn't have tools to write light emitting shaders.

As seen in that comment: https://github.com/DaemonEngine/Daemon/issues/322#issue-604204529

Here is the kind of model that is used in the metro map, as seen in the editor:

![20200421-170352-447 netradiant-metro](https://github.com/user-attachments/assets/4c172bc4-89ca-4734-bcb3-8fb1315d1056)

One can clearly see the floating light emitting shader. That surface is part of the model.

Using an extra surface that is part of the model and this extra surface using a light emitting shader is a trick to permanently attach a light to a model, so importing a model always imports the light.

To make the shader a light emitting shader, one should not need a lightmap stage, but some `q3map_` keywords like `q3map_surfacelight 5000`.

But, for some reasons people creating those assets added a real lightmap stage. I don't know why. Maybe as a workaround for something, or because of some cargo cult.

**Comment by slipher** [comment] 2024-11-08 01:53
Maybe we can delete any lightmap with a multiplicative (`blendfunc filter`) blend as a first stage? That is, shaders which blend a lightmap with the background. The Procyon starchart issues are also caused by a pointless lightmap initial stage.

**Comment by illwieckz** [comment] 2024-11-09 16:23
> Maybe we can delete any lightmap with a multiplicative (`blendfunc filter`) blend as a first stage? That is, shaders which blend a lightmap with the background. The Procyon starchart issues are also caused by a pointless lightmap initial stage.

Maybe doing it is correct to do this if after that you multiply with a color map? As `( background * lightmap ) * colormap == background * ( colormap * lightmap )` . I may have faced some of them because when I rewrote the collapse code I made sure the first case was collapsed as the second one.

**Closed** 2024-11-13 22:21 UTC
Labels: T-Bug, S-Help-Wanted, A-Renderer
